### ISSUE TITLE
Three detectron2 model weights

### ISSUE THREAD

**Issue by Bennett0626** [laurenok24/NSAQA#3]
Thank you for your great work!    I tried to run your code, but I didn't find these three models:
[diver_model_final.pth, plat_model_final.pth, splash_model_final.pth] in ./models/detectron2/model_weights/.
Where can I download them?

**Comment by ParitoshParmar** [comment]
Hi @Byron1201 : Thank you very much for the kind words and interest in our work! You need to download the weights from the links mentioned in the readme.txt file. Let me know if you still face any problems. Cheers!

**Comment by Bennett0626** [comment]
Thank you very much for your reply. I have found it.

**Comment by sweetpiger** [comment]
Hello, did your code run successfully? I would like to ask how you imported the config module.I encountered the following issue that hasn't been resolved yet. 
ModuleNotFoundError: No module named 'config'
