### ISSUE TITLE
How to find supplementary materials

### ISSUE THREAD

**Issue by sizhongzhang1** [laurenok24/NSAQA#4]
Your work is excellent, I was reading your paper and saw that you put more implementation details in the supplementary material, where can I find them please!

**Comment by ParitoshParmar** [comment]
Hi @sizhongzhang1 : Thanks for the kind words! Supplementary material: https://openaccess.thecvf.com/content/CVPR2024W/CVsports/supplemental/Okamoto_Hierarchical_NeuroSymbolic_Approach_CVPRW_2024_supplemental.pdf
